---
- name: Install Japanese fonts and language support
  apt:
    name: "{{ japanese_packages }}"
    state: present
  vars:
    japanese_packages:
      - fonts-noto-cjk
      - fonts-noto-cjk-extra
      - fonts-ipafont
      - fonts-ipafont-gothic
      - fonts-ipafont-mincho
      - fonts-ipaexfont
      - fonts-ipaexfont-gothic
      - fonts-ipaexfont-mincho
      - fonts-vlgothic
      - locales
      - task-japanese
      - task-japanese-desktop

- name: Ensure Japanese locale is present in locale.gen
  lineinfile:
    path: /etc/locale.gen
    regexp: '^#?\s*ja_JP.UTF-8 UTF-8'
    line: 'ja_JP.UTF-8 UTF-8'
    state: present

- name: Generate Japanese locale
  command: locale-gen ja_JP.UTF-8
  changed_when: false

- name: Update font cache
  command: fc-cache -f -v
  changed_when: false