---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present
  vars:
    base_packages:
      - wget
      - curl
      - git
      - build-essential
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - gnupg2

- name: Install Go dependencies
  become: false
  command:
    cmd: "{{ item }}"
    chdir: /workspace/
  with_items:
    - go get github.com/chromedp/chromedp
    - go get github.com/schollz/progressbar/v3
