---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - curl
    - git
    - build-essential
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - gnupg2
    - zip
    - unzip
    - tar
    - python3-pip
    - ansible-lint
